
```{r}
# Libraries
library("ffanalytics")
```

```{r}
# Local variables
# NFL Week
nfl_week = floor(as(difftime(as.Date(Sys.Date(), tz="UTC"), as.Date("2017-08-31", tz="UTC"), units = "weeks"), "numeric"))

# Month
month <- as(format(Sys.Date(), "%m"), "numeric")

# Year
year <- as(format(Sys.Date(), "%Y"), "numeric")
```

```{r}
# League Scoring Settings
userScoring <- list(
  
   QB = data.table::data.table(dataCol = c("passYds", "passTds", "passInt", "rushYds", "rushTds", "twoPts", "fumbles"),
                               multiplier = c(1/25, 4, -2, 1/10, 6, 2, -2)),
   
   RB = data.table::data.table(dataCol = c("rushYds", "rushTds", "rec", "recYds", "recTds", "returnTds", "twoPts", "fumbles"),
                               multiplier = c(1/10, 6, 1, 1/10, 6, 6, 2, -2)),
   
   WR = data.table::data.table(dataCol = c("rushYds", "rushTds", "rec", "recYds", "recTds", "returnTds", "twoPts", "fumbles"),
                               multiplier = c(1/10, 6, 1, 1/10, 6, 6, 2, -2)),
   
   TE = data.table::data.table(dataCol = c("rushYds", "rushTds", "rec", "recYds", "recTds", "returnTds", "twoPts", "fumbles"),
                               multiplier = c(1/10, 6, 1, 1/10, 6, 6, 2, -2)),
   
   K = data.table::data.table(dataCol = c("xp", "fg0019", "fg2029", "fg3039", "fg4049", "fg50", "fgMiss"),
                              multiplier = c(1,  3, 3, 3, 4, 5, -1)),
   
   DST = data.table::data.table(dataCol = c("dstFumlRec", "dstInt", "dstSafety", "dstSack", "dstTd", "dstBlk"),
                                multiplier = c(2, 2, 2, 1, 6, 1.5)),
   ptsBracket = data.table::data.table(threshold = c(0, 6, 13, 17, 27, 34, 45, 99),
                                       points = c(5, 4, 3, 1, 0, -1, -3, -5)))
```


```{r}
# Remove warnings to prevent further lagging
options(warn = -1)

# Scrape projections from a multitude of websites
myProjections <- getProjections(scrapeData=runScrape(week = nfl_week, season = year, analysts = c(-1, 3, 4, 5, 6, 7, 9, 18), positions = c("QB", "RB", "WR", "TE", "K", "DST")), avgMethod = "weighted", getADP = FALSE, leagueScoring = userScoring, vorBaseline, vorType, teams = 10, format = "ppr", mflMocks = -1, mflLeagues = -1, adpSources = NULL)
```